//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace emprestimoModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class emprestimoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new emprestimoEntities object using the connection string found in the 'emprestimoEntities' section of the application configuration file.
        /// </summary>
        public emprestimoEntities() : base("name=emprestimoEntities", "emprestimoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new emprestimoEntities object.
        /// </summary>
        public emprestimoEntities(string connectionString) : base(connectionString, "emprestimoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new emprestimoEntities object.
        /// </summary>
        public emprestimoEntities(EntityConnection connection) : base(connection, "emprestimoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cliente> clientes
        {
            get
            {
                if ((_clientes == null))
                {
                    _clientes = base.CreateObjectSet<cliente>("clientes");
                }
                return _clientes;
            }
        }
        private ObjectSet<cliente> _clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<emprestimo> emprestimoes
        {
            get
            {
                if ((_emprestimoes == null))
                {
                    _emprestimoes = base.CreateObjectSet<emprestimo>("emprestimoes");
                }
                return _emprestimoes;
            }
        }
        private ObjectSet<emprestimo> _emprestimoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<equipamento> equipamentoes
        {
            get
            {
                if ((_equipamentoes == null))
                {
                    _equipamentoes = base.CreateObjectSet<equipamento>("equipamentoes");
                }
                return _equipamentoes;
            }
        }
        private ObjectSet<equipamento> _equipamentoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToclientes(cliente cliente)
        {
            base.AddObject("clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emprestimoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemprestimoes(emprestimo emprestimo)
        {
            base.AddObject("emprestimoes", emprestimo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the equipamentoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToequipamentoes(equipamento equipamento)
        {
            base.AddObject("equipamentoes", equipamento);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="emprestimoModel", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cliente object.
        /// </summary>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        public static cliente Createcliente(global::System.Int32 idCliente)
        {
            cliente cliente = new cliente();
            cliente.IdCliente = idCliente;
            return cliente;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cpf
        {
            get
            {
                return _Cpf;
            }
            set
            {
                OnCpfChanging(value);
                ReportPropertyChanging("Cpf");
                _Cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cpf");
                OnCpfChanged();
            }
        }
        private global::System.String _Cpf;
        partial void OnCpfChanging(global::System.String value);
        partial void OnCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cidade
        {
            get
            {
                return _cidade;
            }
            set
            {
                OncidadeChanging(value);
                ReportPropertyChanging("cidade");
                _cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cidade");
                OncidadeChanged();
            }
        }
        private global::System.String _cidade;
        partial void OncidadeChanging(global::System.String value);
        partial void OncidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="emprestimoModel", Name="emprestimo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class emprestimo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new emprestimo object.
        /// </summary>
        /// <param name="idEmprestimo">Initial value of the IdEmprestimo property.</param>
        /// <param name="idCliente">Initial value of the IdCliente property.</param>
        /// <param name="idEquipamento">Initial value of the IdEquipamento property.</param>
        /// <param name="dataEmprestimo">Initial value of the DataEmprestimo property.</param>
        /// <param name="quantidade">Initial value of the Quantidade property.</param>
        public static emprestimo Createemprestimo(global::System.Int32 idEmprestimo, global::System.Int32 idCliente, global::System.Int32 idEquipamento, global::System.DateTime dataEmprestimo, global::System.Int32 quantidade)
        {
            emprestimo emprestimo = new emprestimo();
            emprestimo.IdEmprestimo = idEmprestimo;
            emprestimo.IdCliente = idCliente;
            emprestimo.IdEquipamento = idEquipamento;
            emprestimo.DataEmprestimo = dataEmprestimo;
            emprestimo.Quantidade = quantidade;
            return emprestimo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmprestimo
        {
            get
            {
                return _IdEmprestimo;
            }
            set
            {
                if (_IdEmprestimo != value)
                {
                    OnIdEmprestimoChanging(value);
                    ReportPropertyChanging("IdEmprestimo");
                    _IdEmprestimo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEmprestimo");
                    OnIdEmprestimoChanged();
                }
            }
        }
        private global::System.Int32 _IdEmprestimo;
        partial void OnIdEmprestimoChanging(global::System.Int32 value);
        partial void OnIdEmprestimoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                OnIdClienteChanging(value);
                ReportPropertyChanging("IdCliente");
                _IdCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCliente");
                OnIdClienteChanged();
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipamento
        {
            get
            {
                return _IdEquipamento;
            }
            set
            {
                OnIdEquipamentoChanging(value);
                ReportPropertyChanging("IdEquipamento");
                _IdEquipamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEquipamento");
                OnIdEquipamentoChanged();
            }
        }
        private global::System.Int32 _IdEquipamento;
        partial void OnIdEquipamentoChanging(global::System.Int32 value);
        partial void OnIdEquipamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataEmprestimo
        {
            get
            {
                return _DataEmprestimo;
            }
            set
            {
                OnDataEmprestimoChanging(value);
                ReportPropertyChanging("DataEmprestimo");
                _DataEmprestimo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataEmprestimo");
                OnDataEmprestimoChanged();
            }
        }
        private global::System.DateTime _DataEmprestimo;
        partial void OnDataEmprestimoChanging(global::System.DateTime value);
        partial void OnDataEmprestimoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantidade
        {
            get
            {
                return _Quantidade;
            }
            set
            {
                OnQuantidadeChanging(value);
                ReportPropertyChanging("Quantidade");
                _Quantidade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantidade");
                OnQuantidadeChanged();
            }
        }
        private global::System.Int32 _Quantidade;
        partial void OnQuantidadeChanging(global::System.Int32 value);
        partial void OnQuantidadeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="emprestimoModel", Name="equipamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class equipamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new equipamento object.
        /// </summary>
        /// <param name="idEquipamnto">Initial value of the IdEquipamnto property.</param>
        public static equipamento Createequipamento(global::System.Int32 idEquipamnto)
        {
            equipamento equipamento = new equipamento();
            equipamento.IdEquipamnto = idEquipamnto;
            return equipamento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipamnto
        {
            get
            {
                return _IdEquipamnto;
            }
            set
            {
                if (_IdEquipamnto != value)
                {
                    OnIdEquipamntoChanging(value);
                    ReportPropertyChanging("IdEquipamnto");
                    _IdEquipamnto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdEquipamnto");
                    OnIdEquipamntoChanged();
                }
            }
        }
        private global::System.Int32 _IdEquipamnto;
        partial void OnIdEquipamntoChanging(global::System.Int32 value);
        partial void OnIdEquipamntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoEquipameno
        {
            get
            {
                return _TipoEquipameno;
            }
            set
            {
                OnTipoEquipamenoChanging(value);
                ReportPropertyChanging("TipoEquipameno");
                _TipoEquipameno = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoEquipameno");
                OnTipoEquipamenoChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoEquipameno;
        partial void OnTipoEquipamenoChanging(Nullable<global::System.Int32> value);
        partial void OnTipoEquipamenoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroSerie
        {
            get
            {
                return _NumeroSerie;
            }
            set
            {
                OnNumeroSerieChanging(value);
                ReportPropertyChanging("NumeroSerie");
                _NumeroSerie = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroSerie");
                OnNumeroSerieChanged();
            }
        }
        private global::System.String _NumeroSerie;
        partial void OnNumeroSerieChanging(global::System.String value);
        partial void OnNumeroSerieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();

        #endregion
    
    }

    #endregion
    
}
